.gitignore, .travis.yml, Dockerfile, Makefile, README.md, cmd/pasta/pasta.go, cmd/pastad/pastad.go, cmd/pastad/storage.go, cmd/pastad/storage__test.go, pastad.toml.example, test/test.sh
Remove sqlite database and turn to file-only backend.
=> Remove sqlite database

Makefile, cmd/pasta/pasta.go, cmd/pasta/storage.go, test/test.sh
Improve the client to remember last pushes and improve the
command line arguments
=> Improve pasta CLI

cmd/pasta/pasta.go, cmd/pasta/storage.go
This PR contains some minor client improvements
=> Client improvements

cmd/pastad/pastad.go, cmd/pastad/storage.go
=> Use crypto/rand

README.md, cloud-init.yaml.example
As we now have [pasta.sh.cvut.cz](https://pasta.sh.cvut.cz/) I'm sharing the steps describing the deployment on [RancherOS](https://rancher.com/docs/os/v1.x/en/).
=> Add RancherOS section to README

Dockerfile, Makefile, cmd/pastad/pastad.go, test/test.sh
Add some simple program arguments for the `pastad` server and update the Dockerfile to user the internally provided `mime.types` file
=> Add program arguments for pastad

cmd/pastad/pastad.go, pastad.toml.example, test/test.sh
Adds a spam protection by limiting the number of requests (POST and DELETE) per IP address
=> Add spam protection

README.md, go.mod, go.sum
* Use go >= 1.13
* Update the README.md
=> Make the OBS build possible

cmd/pasta/pasta.go, cmd/pasta/storage.go, cmd/pastad/pastad.go, test/test.sh
Pastas will expire now also on the client side (https://github.com/grisu48/pasta/issues/22)
=> Expire pastas on client side

Dockerfile, Makefile
Base the container on scratch and build a static binary
=> Make tiny containers

README.md, cmd/pastad/pastad.go, test/test.sh
Add support for configuring pastad via environmenal variables.
=> Add support for environmental vars

.github/workflows/pastad.yml, cmd/pastad/pastad.go
Adds a text area to the index page so people can just dump stuff there
without uploading a file.
Implements https://github.com/grisu48/pasta/issues/32
=> Add textarea to index page

README.md
Include code steps on how to setup pasta and improve the wording.
=> Improve the deployment documentation

cmd/pastad/pastad.go
Fix the issue that the web upload was not working. The issue was coming
from overwriting the multibody reader with `r.Body`.
* Related ticket: https://github.com/grisu48/pasta/issues/44
=> Fix upload not working issue

cmd/pastad/pastad.go, cmd/pastad/storage.go, pastad.toml.example, test/test.sh
Add public pastas which are listed on the main page.
=> Add public pastas

cmd/pasta/pasta.go, cmd/pastad/pastad.go
=> Add version and make them consistent

cmd/pasta/pasta.go
`pasta rm` can now handle a given range, e.g. `pasta rm 3-7` for deleting the entries 3,4,5,6,7.
=> Add range for rm

Dockerfile
Let's eat our own dog-food ;-)
=> Build pasta in bci/golang

Containerfile, Dockerfile, Makefile
Lint Dockerfile and rename it to Containerfile
=> Lint Dockerfile

.github/workflows/ghcr.yml
=> Add amd64/arm64 multiarch to GHCR
